server:
  port: 8083
  tomcat:
    uri-encoding: UTF-8   # 配置Tomcat编码,默认为UTF-8
    max-threads: 1000  # 配置最大线程数
    
spring:
  mvc:
    view:
      prefix: /WEB-INF/webpage/  
      suffix: .jsp  
  thymeleaf: #关闭默认模板引擎
    cache: false
    enabled: false
  devtools:
    restart: #热部署生效
       enabled: true
       #additional-paths: src/main/java   #设置重启的目录
       #classpath   #目录下的WEB-INF文件夹内容修改不重启
       exclude: WEB-INF/**
  aop:
    auto: true
  dataSource: #数据源
    zuprbac:  
      type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://172.18.36.239:3306/zuprbac?useUnicode=true&characterEncoding=UTF-8
      username: root
      password: iesapp
      initialSize: 50 
      maxActive: 200 
      maxIdle: 10 
      maxWait: 80 
      validationQuery: SELECT 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 25200000
      removeAbandoned: true
      removeAbandonedTimeout: 1800
      defaultAutoCommit: true
      logAbandoned: true
    zupwf:  
      type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://172.18.36.239:3306/zupwf?useUnicode=true&characterEncoding=UTF-8
      username: root
      password: iesapp
      initialSize: 50 
      maxActive: 200 
      maxIdle: 10 
      maxWait: 80 
      validationQuery: SELECT 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 25200000
      removeAbandoned: true
      removeAbandonedTimeout: 1800
      defaultAutoCommit: true
      logAbandoned: true
    mysql1: 
      type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://172.18.36.239:3306/pms?useUnicode=true&characterEncoding=UTF-8
      username: root
      password: iesapp
      initialSize: 50 
      maxActive: 200 
      maxIdle: 10 
      maxWait: 80 
      validationQuery: SELECT 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 25200000
      removeAbandoned: true
      removeAbandonedTimeout: 1800
      defaultAutoCommit: true
      logAbandoned: true
#mybatis:
  #mapper-locations: classpath:zup-mybatis.xml
  #type-aliases-package: cn.zoneday.mgeids.entity
application:
  message: Hello BJ 
  
  